### PR TITLE
Modify server routes to reflect client-server contract

### PR DESCRIPTION
**Pull request by onelovelyname**

### CODE REVIEW

**Comment by jyeg** [comment]
We using Bluebird now? Otherwise dont let me stand in your way.

**Comment by kevhuang** [comment]
@onelovelyname Perhaps we should use an environment variable for the database URL. For example:

```
mongoURI = process.env.DATABASE_URL || 'mongodb://localhost/courageoustrapezedb';
mongoose.connect(mongoURI);
```

The environment variable will be defined in Azure.

**Comment by mwharris1313** [comment]
Just a question on server/users/userModel.js
Should messages and contacts be in the userModel?
If these are just temporary stubs to messages/contacts collections (not sure how mongo/mongoose implements that connection) then I'll go with it.

**Comment by mwharris1313** [comment]
Thumbs Up.

**Comment by kevhuang** [comment]
@onelovelyname as discussed, let's incorporate the environment variable for the database in the next pull request. I'll be merging this so we have a base for the server.

**Comment by jyeg** [comment]
go for it

**Pull request merged**
