### PR TITLE
Updated package.json file for BSD-3 Clause 

### PR DESCRIPTION
**Pull request by onelovelyname**

### CODE REVIEW

**Comment by kevhuang** [comment]
Cool cool

**Comment by jyeg** [comment]
solid-core

**Comment by mwharris1313** [comment]
b

**Comment by kevhuang** [comment]
@onelovelyname one thing I just noticed was that the bcrypt version is 0.0.3. I don't know if that will cause any issues, but feel free to adjust the version if needed later on.

**Comment by kevhuang** [comment]
@onelovelyname disregard my comment about the bcrypt version. I was looking at a README for a different bcrypt package. 0.0.3 is the latest for bcrypt-nodejs.

**Pull request merged**
