### PR TITLE
Update press release to reflect the updated product features for MVP

### PR DESCRIPTION
**Pull request by kevhuang**
@jyeg @mwharris333 @onelovelyname Feel free to make comments on this revised press release based on the new direction we're taking with the product.

### CODE REVIEW

**Comment by kevhuang** [comment]
Just realized I forgot to add some info about the mobile app. Here's an updated version:

# Greenfield Project

## Socialite

Socialite targets anyone who is too busy or forgetful to send out personal communications to their friends and family.

## Summary

Socialite allows you to schedule text messages with your closest contacts.

Features:
- Schedule text messages for specific dates and times in advance
- Batch manage communications
- Import contacts from Google Contacts
- Schedule one-time and recurring correspondence
- Review and send all scheduled messages for the day in one click from your mobile device

## Problem

It is difficult to maintain social relationships and communications with friends and family during our busy lives.

## Solution

Our technology allows you to plan your social communications in one sitting and eliminates communication breakdowns.

## Quotes from Courageous Trapeze

“Let our technology maintain your social connections for you.”

"Never forget a birthday or special occasion again."

“Social ties are the keys to happiness in life.”

## How to Get Started

Import your contacts from Google Contacts and select connections with whom you would like to stay in contact. Schedule that communication for up to a year in advance with only a couple clicks. 

To quickly get started, follow these simple steps:
1. Log in
2. Enter contacts and/or import from Google Contacts
3. Select contacts you want to send messages to
4. Type a personal message or select from a collection of prepared messages
5. Schedule a date and time to send the message
6. Launch the app on your mobile device to review all scheduled messages for the day
7. Review scheduled messages and choose to send individual messages or all at once

## Customer Quotes

“I scheduled out birthday and holiday greetings for my closest friends and family months in advance. No longer am I forgetting important milestones!” 

"I no longer have to worry about forgetting to send my friends birthday wishes."

“I will never get a passive-aggressive text from my parents again, thanks!”

## Closing and Call to Action

Time is fleeting. Social connections, albeit time consuming, are critical. Take the overhead of contact management out of the equation. Who wouldn’t want a personal assistant? Now you can be your own personal assistant to the future you...in bots we trust.  

Ever unintentionally fallen out of contact with someone? Everyone has. What if I could guarantee that you will never be the person at fault for the loss of connection again? With Socialite personal correspondence management, track and schedule your communications.

If you need any additional assistance, please read our FAQ.

**Comment by jyeg** [comment]
okie dokie

**Comment by mwharris1313** [comment]
Thumbs up.

**Comment by onelovelyname** [comment]
Thanks for updating, Kevin - looks good

**Pull request merged**
